### PR TITLE
feat(pwa): implement precache

### PR DESCRIPTION
**Pull request by charlesrocket**
Without network information for now.

### CODE REVIEW

**Review by charlesrocket — COMMENTED** [review]
Cache size is good.

**Comment by Jieiku** [comment]
Awesome, I see how you did that too, I had not considered that approach because I thought I needed to pass all documents, and figured the list would be too big for example in the data-cache you have:

I cannot tell if it is working on the demo, it does not seem to be.

I opened chrome on my android device and visited https://halve-z.netlify.app  I then waited 10 seconds which should be plenty of time for the service worker to download assets, and then disabled the data and wifi on my phone. none of the pages like posts or code load, it just shows Offline Mode, no cache/page found.

I did look at the code and see the intended implementation though, and have done similar things, it does look like it should be working at first glance.

**Comment by Jieiku** [comment]
Works now for me, I can navigate between the Home, Posts, and Code Pages. I can also browse any of the articles!

One thing I really like about the PWA approach in addition to being able to use my site while offline, is that page navigation is instantaneous, heavy bloated sites would never want to use this approach, especially with lots of content, but with these lightweight zola generated static sites the user experience is really improved when everything is cached, all navigation is instantaneous!

**Comment by charlesrocket** [comment]
@Jieiku Swell! For heavy sites, it would definitely be a drag, true. For such cases, maybe precache critical assets only and prefetch images, etc., depending on `head` conditionals?

**Comment by Jieiku** [comment]
yeah, that sounds about right to me, when I was reading about service workers and PWA's, one idea was to have the service worker cache the pages that are linked on a given page, that was as you browse any link you could possibly click on that page would get pre-cached. (assuming it is on the same domain)

**Comment by charlesrocket** [comment]
@Jieiku text assets for the win! It might get out of hands in my case—some images are big, though this could be resolved with the `zola` image processor.

**Review by charlesrocket — COMMENTED** [review]
Dynamic cache worked flawlessly, until I started implementing paginators (#26). I need a break...

**Comment by fiaz-ali** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
kenrube, @davidpanzarella, @bntzio, @mkg-gh, @Friizi, @sambacha, @JBader89, @sturm3nta, @hongyingcheng, @miljantekic, @eddiana, @mAlkhatieb, @huangkaiqiao, @sanjaykumari, @pioug, @ThomasFMH, @Hugoo, @alitaheri, @Locustsgogogo, @JoKacar, @toreserter, @dniswhite, @DeRain, @shovanch, @ryanoasis, @orhanoksuzz, @andreamorosati, @ignaciocasal, @hyperjiang, @MilleniumSpark, @RocketCat86, @matthieuh, @adman9000, @cruzdanilo, @ace-subido, @tesths, @shootout, @artola, @tongfeif, @ue, @rubenmoya, @Bicco, @mekery, @randysu, @Ly0n, @alsco77, @aiwozhe, @chfw, @MarekJCK, @spasma

**Pull request merged**
